#!/usr/bin/env python3
"""CJK-safe SVG → PNG helpers (fontconfig + style injection)."""
from __future__ import annotations

import os
import re
import subprocess
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
FONTS_DIR = Path(__file__).resolve().parent / "fonts"
FONT_FILE = FONTS_DIR / "NotoSansCJKsc-Regular.otf"
FONTCONF = FONTS_DIR / "fonts.conf"
FONT_CACHE_DIR = Path("/tmp/fontconfig-deepseek-everything-png")
FONT_URL = (
    "https://github.com/notofonts/noto-cjk/raw/main/"
    "Sans/OTF/SimplifiedChinese/NotoSansCJKsc-Regular.otf"
)
CJK_STACK = "Noto Sans CJK SC, Noto Sans SC, sans-serif"
_FONTCONFIG_READY = False


def write_fontconfig() -> None:
    """Write fonts.conf from repo-relative paths (never commit this file)."""
    fonts_dir = FONTS_DIR.resolve()
    FONTCONF.write_text(
        "<?xml version=\"1.0\"?>\n"
        "<!-- Auto-generated by scripts/svg/cjk_png.py — do not edit or commit -->\n"
        "<!DOCTYPE fontconfig SYSTEM \"fonts.dtd\">\n"
        "<fontconfig>\n"
        f"  <dir>{fonts_dir}</dir>\n"
        "  <dir>/usr/share/fonts/opentype/noto</dir>\n"
        "  <dir>/usr/share/fonts/truetype/noto</dir>\n"
        f"  <cachedir>{FONT_CACHE_DIR}</cachedir>\n"
        "</fontconfig>\n",
        encoding="utf-8",
    )


def ensure_cjk_font() -> None:
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    if not FONT_FILE.is_file() or FONT_FILE.stat().st_size < 1_000_000:
        print(f"fetching CJK font -> {FONT_FILE}")
        urllib.request.urlretrieve(FONT_URL, FONT_FILE)
    write_fontconfig()


def setup_fontconfig() -> None:
    global _FONTCONFIG_READY
    if _FONTCONFIG_READY:
        return
    ensure_cjk_font()
    os.environ["FONTCONFIG_FILE"] = str(FONTCONF)
    FONT_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    subprocess.run(["fc-cache", "-f"], check=False, capture_output=True)
    _FONTCONFIG_READY = True


def prepare_svg_for_png(text: str) -> str:
    """Inject CJK font stack so cairo/librsvg can render 中文 labels."""
    if "Noto Sans CJK SC" not in text:
        text = text.replace(
            "system-ui, -apple-system, sans-serif",
            f"Noto Sans CJK SC, system-ui, sans-serif",
        )
        text = text.replace(
            "system-ui, sans-serif",
            "Noto Sans CJK SC, system-ui, sans-serif",
        )
        text = re.sub(
            r"(font:\s*[^;{]*?)sans-serif",
            rf"\1{CJK_STACK}",
            text,
        )
        text = re.sub(
            r"(font-family:\s*[^;{]*?)sans-serif",
            rf"\1{CJK_STACK}",
            text,
        )
        if not re.search(r"<svg[^>]*\sfont-family=", text[:1200]):
            text = re.sub(
                r"(<svg\b)",
                rf'\1 font-family="{CJK_STACK}"',
                text,
                count=1,
            )
    return text


def svg_to_png(svg: Path, out: Path, *, output_width: int = 1840) -> None:
    import cairosvg

    setup_fontconfig()
    raw = svg.read_text(encoding="utf-8")
    prepared = prepare_svg_for_png(raw)
    out.parent.mkdir(parents=True, exist_ok=True)
    cairosvg.svg2png(
        bytestring=prepared.encode("utf-8"),
        write_to=str(out),
        output_width=output_width,
    )
