#!/usr/bin/env python3
"""Strip inline SVG from qa md; write <img src="...svg"> stubs (default).

PNG rasterization is opt-in only: pass --png when the user explicitly asks.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parent / "reference"))
from _paths import ENGRAM_DIAGRAMS, REPO  # noqa: E402

import argparse
import os
import re
import subprocess
import sys
import urllib.request
from pathlib import Path

try:
    import cairosvg
except ImportError:
    cairosvg = None  # type: ignore

FONTS_DIR = ENGRAM_DIAGRAMS / "fonts"
QA = REPO / "docs" / "material" / "papers" / "engram" / "qa"
FONT_FILE = FONTS_DIR / "NotoSansCJKsc-Regular.otf"
FONTCONF = FONTS_DIR / "fonts.conf"
FONT_URL = (
    "https://github.com/notofonts/noto-cjk/raw/main/"
    "Sans/OTF/SimplifiedChinese/NotoSansCJKsc-Regular.otf"
)
_FONTCONFIG_READY = False

INLINE_BLOCK = re.compile(
    r'<div(?: markdown="0")? align="center">\s*\n+'
    r'(?:<!-- inline: [^ ]+\.svg -->\s*\n)?'
    r'<svg[\s\S]*?</svg>\s*\n+'
    r'</div>\s*\n+'
    r'(?:\[图示详情\]\((?P<link>[^)]+)\)\s*\n*)?',
    re.MULTILINE,
)

IMG_STUB = re.compile(
    r'<img src="(?P<src>[^"]+)" alt="(?P<alt>[^"]*)"\s+width="(?P<width>\d+)"/>\s*\n+'
    r'\[图示详情\]\((?P<link>[^)]+)\)',
    re.MULTILINE,
)


def ensure_cjk_font() -> None:
  """Download Noto Sans CJK SC if missing (only needed for --png)."""
  FONTS_DIR.mkdir(parents=True, exist_ok=True)
  if not FONT_FILE.is_file() or FONT_FILE.stat().st_size < 1_000_000:
    print(f"fetching CJK font -> {FONT_FILE}")
    urllib.request.urlretrieve(FONT_URL, FONT_FILE)
  if not FONTCONF.is_file():
    FONTCONF.write_text(
      '<?xml version="1.0"?>\n'
      '<!-- Auto-generated by publish_diagrams.py — do not edit or commit -->\n'
      '<!DOCTYPE fontconfig SYSTEM "fonts.dtd">\n'
      "<fontconfig>\n"
      f"  <dir>{FONTS_DIR.resolve()}</dir>\n"
      "  <cachedir>/tmp/fontconfig-engram-diagrams</cachedir>\n"
      "</fontconfig>\n",
      encoding="utf-8",
    )


def setup_fontconfig() -> None:
  global _FONTCONFIG_READY
  if _FONTCONFIG_READY:
    return
  ensure_cjk_font()
  os.environ["FONTCONFIG_FILE"] = str(FONTCONF)
  subprocess.run(["fc-cache", "-f"], check=False, capture_output=True)
  _FONTCONFIG_READY = True


def svg_to_png(svg: Path, width: int = 920) -> Path:
  png = svg.with_suffix(".png")
  if cairosvg is None:
    raise SystemExit("pip install cairosvg")
  setup_fontconfig()
  cairosvg.svg2png(url=str(svg), write_to=str(png), output_width=width)
  return png


def diagram_img_block(svg_rel: str, alt: str, width: int = 920, *, use_png: bool = False) -> str:
  src = svg_rel.replace(".svg", ".png") if use_png else svg_rel
  return (
    f'<img src="{src}" alt="{alt}" width="{width}"/>\n\n'
    f"[图示详情]({svg_rel})\n"
  )


def strip_inline_to_img(md_path: Path, *, use_png: bool = False) -> bool:
  text = md_path.read_text(encoding="utf-8")
  md_dir = md_path.parent
  changed = False

  def repl_inline(m: re.Match[str]) -> str:
    nonlocal changed
    changed = True
    link = m.group("link")
    if not link:
      return ""
    name = Path(link).name
    alt = {
      "engram-01e-residual-step78.svg": "Step 7-8 残差与 backbone 写回",
      "engram-01f-rf10-train-infer.svg": "RF 1 vs 10 训练与推理",
      "engram-01g-rf-one-position.svg": "位置 t 感受野 1 到 10",
      "engram-01h-rf-change-impact.svg": "感受野 1 到 10 影响总览",
    }.get(name, name)
    w = 920 if "01f" in name or "01h" in name else 860
    svg_path = (md_dir / link).resolve()
    if use_png and svg_path.is_file() and cairosvg:
      svg_to_png(svg_path, w)
    return diagram_img_block(link, alt, w, use_png=use_png)

  new_text = INLINE_BLOCK.sub(repl_inline, text)
  if changed:
    md_path.write_text(new_text, encoding="utf-8")
  return changed


def normalize_img_refs(md_path: Path, *, use_png: bool = False) -> int:
  """Ensure <img src> points at svg (default) or png (--png); refresh png if requested."""
  text = md_path.read_text(encoding="utf-8")
  md_dir = md_path.parent
  n = 0

  def repl_img(m: re.Match[str]) -> str:
    nonlocal n
    link = m.group("link")
    alt = m.group("alt")
    width = int(m.group("width"))
    want_src = link.replace(".svg", ".png") if use_png else link
    svg_path = (md_dir / link).resolve()
    if use_png and svg_path.is_file() and cairosvg:
      svg_to_png(svg_path, width)
    if m.group("src") != want_src:
      n += 1
      return diagram_img_block(link, alt, width, use_png=use_png)
    return m.group(0)

  new_text = IMG_STUB.sub(repl_img, text)
  if n:
    md_path.write_text(new_text, encoding="utf-8")
  return n


def main(argv: list[str] | None = None) -> int:
  parser = argparse.ArgumentParser(description=__doc__)
  parser.add_argument("md", nargs="*", type=Path, help="qa markdown files (default: qa/*.md)")
  parser.add_argument(
    "--png",
    action="store_true",
    help="rasterize to PNG and point <img> at .png (only when user explicitly asks)",
  )
  args = parser.parse_args(argv)
  targets = args.md if args.md else sorted(QA.glob("*.md"))
  for p in targets:
    if strip_inline_to_img(p, use_png=args.png):
      print(f"stripped inline -> img: {p}")
    else:
      k = normalize_img_refs(p, use_png=args.png)
      if k:
        kind = "png" if args.png else "svg"
        print(f"normalized {k} img ref(s) to {kind}: {p}")
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
